/**
 *		
 */
package com.easy;

/**
 *
Author: 
	Sunny Shah 
	sunnyshah452@gmail.com 
	https://github.com/sunnyshah2894
	https://leetcode.com/sunnyshah28
	https://www.linkedin.com/in/sunnyshah28
 *
 *
-------------------------------------------------------
https://leetcode.com/problems/find-the-difference/description/
-------------------------------------------------------

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.


*
*/
public class FindTheDifference {
	public char findTheDifference(String s, String t) {
        int count[] = new int[26];
        for( char c: s.toCharArray() )
            count[ c-'a']++;
        for( char c: t.toCharArray() )
            count[c-'a']--;
        
        for( int i=0; i<26 ; i++ ){
            if( count[i] != 0 )
                return (char)('a'+i);
        }
        return 0;
    }
}
